language: go
sudo: required
go: 
  - 1.9
branches:
  only:
  - master
services:
  - docker
before_install:
  - go get github.com/mattn/goveralls
  - docker pull uber/go-torch
script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go test -bench=. -cpuprofile='cpu.prof' -memprofile='mem.prof'
after_script:
  - docker run uber/go-torch -s $HOME/gopath/src/github.com/RossMerr/Caudex.GraphBLAS/Caudex.GraphBLAS.test 'cpu.prof' -p > prof/torch.svg